APPLICATION_ID: pojo
service_description:
  name: pojo
  version: 0.0.1
  properties:
    allowCrossApp: false
spring:
  main:
    web-application-type: none
servicecomb:
  service:
    registry:
      address: https://cse.cn-north-1.myhuaweicloud.com
      instance:
        watch: false
  config:
    client:
      serverUri: https://cse.cn-north-1.myhuaweicloud.com
      refreshMode: 1
      refresh_interval: 5000
  #monitor:
    #client:
      #serverUri: https://cse.cn-north-1.myhuaweicloud.com
  rest:
    address: 0.0.0.0:8080
  #When a local project is deployed as a container outside a cluster, you need to delete all monitor and credentials comments and configure the AK/SK.
  #credentials:
    #accessKey: ak
    #secretKey: sk
    #akskCustomCipher: default
    #project: default
